required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
]

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "release-6.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "release-1.9"

[[constraint]]
  name = "github.com/micro/go-grpc"
  version = "0.3.0"

[[constraint]]
  name = "github.com/micro/go-micro"
  version = "0.9.0"

[[constraint]]
  name = "github.com/micro/go-plugins"
  version = "0.11.0"

[prune]
  go-tests = true
  #unused-packages = true
