// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/magaldima/macro/pkg/apis/microservice/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMicroServices implements MicroServiceInterface
type FakeMicroServices struct {
	Fake *FakeMicroV1alpha1
	ns   string
}

var microservicesResource = schema.GroupVersionResource{Group: "micro.mu", Version: "v1alpha1", Resource: "microservices"}

var microservicesKind = schema.GroupVersionKind{Group: "micro.mu", Version: "v1alpha1", Kind: "MicroService"}

// Get takes name of the microService, and returns the corresponding microService object, and an error if there is any.
func (c *FakeMicroServices) Get(name string, options v1.GetOptions) (result *v1alpha1.MicroService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(microservicesResource, c.ns, name), &v1alpha1.MicroService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MicroService), err
}

// List takes label and field selectors, and returns the list of MicroServices that match those selectors.
func (c *FakeMicroServices) List(opts v1.ListOptions) (result *v1alpha1.MicroServiceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(microservicesResource, microservicesKind, c.ns, opts), &v1alpha1.MicroServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MicroServiceList{}
	for _, item := range obj.(*v1alpha1.MicroServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested microServices.
func (c *FakeMicroServices) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(microservicesResource, c.ns, opts))

}

// Create takes the representation of a microService and creates it.  Returns the server's representation of the microService, and an error, if there is any.
func (c *FakeMicroServices) Create(microService *v1alpha1.MicroService) (result *v1alpha1.MicroService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(microservicesResource, c.ns, microService), &v1alpha1.MicroService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MicroService), err
}

// Update takes the representation of a microService and updates it. Returns the server's representation of the microService, and an error, if there is any.
func (c *FakeMicroServices) Update(microService *v1alpha1.MicroService) (result *v1alpha1.MicroService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(microservicesResource, c.ns, microService), &v1alpha1.MicroService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MicroService), err
}

// Delete takes name of the microService and deletes it. Returns an error if one occurs.
func (c *FakeMicroServices) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(microservicesResource, c.ns, name), &v1alpha1.MicroService{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMicroServices) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(microservicesResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MicroServiceList{})
	return err
}

// Patch applies the patch and returns the patched microService.
func (c *FakeMicroServices) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MicroService, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(microservicesResource, c.ns, name, data, subresources...), &v1alpha1.MicroService{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MicroService), err
}
