// Code generated by lister-gen. DO NOT EDIT.

// This file was automatically generated by lister-gen

package v1alpha1

// MicroServiceListerExpansion allows custom methods to be added to
// MicroServiceLister.
type MicroServiceListerExpansion interface{}

// MicroServiceNamespaceListerExpansion allows custom methods to be added to
// MicroServiceNamespaceLister.
type MicroServiceNamespaceListerExpansion interface{}
