// Code generated by informer-gen. DO NOT EDIT.

// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	microservicev1alpha1 "github.com/magaldima/macro/pkg/apis/microservice/v1alpha1"
	versioned "github.com/magaldima/macro/pkg/client/clientset/versioned"
	internalinterfaces "github.com/magaldima/macro/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/magaldima/macro/pkg/client/listers/microservice/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MicroServiceInformer provides access to a shared informer and lister for
// MicroServices.
type MicroServiceInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MicroServiceLister
}

type microServiceInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMicroServiceInformer constructs a new informer for MicroService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMicroServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMicroServiceInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMicroServiceInformer constructs a new informer for MicroService type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMicroServiceInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MicroV1alpha1().MicroServices(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MicroV1alpha1().MicroServices(namespace).Watch(options)
			},
		},
		&microservicev1alpha1.MicroService{},
		resyncPeriod,
		indexers,
	)
}

func (f *microServiceInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMicroServiceInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *microServiceInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&microservicev1alpha1.MicroService{}, f.defaultInformer)
}

func (f *microServiceInformer) Lister() v1alpha1.MicroServiceLister {
	return v1alpha1.NewMicroServiceLister(f.Informer().GetIndexer())
}
